"use client";

import { useMemo, useState } from "react";
import { BrandModal } from "./brand-modal";
import { ProductModal } from "./product-modal";
import type { BrandOptionDTO, ProductOptionDTO } from "../contracts";

async function createBrandRemote(input: { code: string; name: string }): Promise<BrandOptionDTO> { const response = await fetch("/api/v2/master-data/brands", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...input, idempotencyKey: crypto.randomUUID() }) }); const body = await response.json() as { data?: BrandOptionDTO; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Không thể tạo nhãn hàng."); return body.data; }
async function createProductRemote(input: { brandId: string; sku: string; name: string }): Promise<ProductOptionDTO> { const response = await fetch("/api/v2/master-data/products", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...input, aliases: [], idempotencyKey: crypto.randomUUID() }) }); const body = await response.json() as { data?: ProductOptionDTO; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Không thể tạo SKU."); return body.data; }

export function MasterDataManager({ initialBrands, initialProducts, onCreateBrand = createBrandRemote, onCreateProduct = createProductRemote }: { initialBrands: BrandOptionDTO[]; initialProducts: ProductOptionDTO[]; onCreateBrand?: (input: { code: string; name: string }) => Promise<BrandOptionDTO>; onCreateProduct?: (input: { brandId: string; sku: string; name: string }) => Promise<ProductOptionDTO> }) {
  const [brands, setBrands] = useState(initialBrands); const [products, setProducts] = useState(initialProducts); const [selectedBrandId, setSelectedBrandId] = useState(initialBrands[0]?.id ?? ""); const [brandOpen, setBrandOpen] = useState(false); const [productOpen, setProductOpen] = useState(false);
  const selectedProducts = useMemo(() => products.filter((product) => product.brandId === selectedBrandId), [products, selectedBrandId]);
  return <section className="master-data-manager"><header className="master-data-manager__toolbar"><div><p className="section-index">Dữ liệu nền</p><h2>Nhãn hàng & SKU</h2><p className="muted">Tạo và duy trì danh mục dùng chung theo đúng phạm vi được cấp quyền.</p></div><div className="master-data-manager__actions"><button type="button" className="button" onClick={() => setBrandOpen(true)}>Thêm nhãn hàng</button><button type="button" className="button button--primary" disabled={!brands.length} onClick={() => setProductOpen(true)}>Thêm SKU</button></div></header><div className="master-data-manager__filters"><label><span>Nhãn hàng đang chọn</span><select aria-label="Nhãn hàng đang chọn" value={selectedBrandId} onChange={(event) => setSelectedBrandId(event.target.value)}>{brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.code} · {brand.name}</option>)}</select></label></div><div className="master-data-manager__grid"><article><h3>Nhãn hàng ({brands.length})</h3>{brands.length ? <ul>{brands.map((brand) => <li key={brand.id}><button type="button" className={brand.id === selectedBrandId ? "is-selected" : ""} onClick={() => setSelectedBrandId(brand.id)}><strong>{brand.code}</strong><span>{brand.name}</span></button></li>)}</ul> : <p className="muted">Chưa có nhãn hàng.</p>}</article><article><h3>SKU thuộc nhãn hàng ({selectedProducts.length})</h3>{selectedProducts.length ? <ul>{selectedProducts.map((product) => <li key={product.id}><strong>{product.canonicalSku}</strong><span>{product.name}</span>{product.aliases.length ? <small>Alias: {product.aliases.join(", ")}</small> : null}</li>)}</ul> : <p className="muted">Chưa có SKU cho nhãn hàng này.</p>}</article></div><BrandModal open={brandOpen} onClose={() => setBrandOpen(false)} onCreated={(brand) => { setBrands((current) => [...current, brand]); setSelectedBrandId(brand.id); }} onCreate={onCreateBrand} /><ProductModal key={`${selectedBrandId}-${productOpen}`} open={productOpen} brands={brands} selectedBrandId={selectedBrandId} onClose={() => setProductOpen(false)} onCreated={(product) => setProducts((current) => [...current, product])} onCreate={onCreateProduct} /></section>;
}
