"use client";

import { useEffect, useRef, useState } from "react";
import { normalizeSku, type BrandOptionDTO, type ProductOptionDTO } from "../contracts";

export function ProductModal({ open, brands, selectedBrandId, onClose, onCreated, onCreate }: { open: boolean; brands: BrandOptionDTO[]; selectedBrandId?: string; onClose: () => void; onCreated: (product: ProductOptionDTO) => void; onCreate: (input: { brandId: string; sku: string; name: string }) => Promise<ProductOptionDTO> }) {
  const [brandId, setBrandId] = useState(selectedBrandId ?? brands[0]?.id ?? ""); const [sku, setSku] = useState(""); const [name, setName] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const firstRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!open) return; firstRef.current?.focus(); const handler = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [open, onClose]);
  if (!open) return null;
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!brandId || !sku.trim() || !name.trim()) { setError("Chọn nhãn hàng và nhập đủ thông tin SKU."); return; } setSaving(true); setError(null); try { onCreated(await onCreate({ brandId, sku: normalizeSku(sku), name: name.trim() })); setSku(""); setName(""); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tạo SKU."); } finally { setSaving(false); } }
  return <div className="master-data-modal" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><form className="master-data-modal__panel" role="dialog" aria-modal="true" aria-label="Thêm SKU" onSubmit={submit}><p className="section-index">Dữ liệu nền</p><h2>Thêm SKU</h2><label><span>Nhãn hàng</span><select aria-label="Nhãn hàng" value={brandId} onChange={(event) => setBrandId(event.target.value)}>{brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.code} · {brand.name}</option>)}</select></label><label><span>Mã SKU</span><input ref={firstRef} aria-label="Mã SKU" value={sku} onChange={(event) => setSku(event.target.value)} placeholder="ET-015025" /></label><label><span>Tên sản phẩm</span><input aria-label="Tên sản phẩm" value={name} onChange={(event) => setName(event.target.value)} placeholder="Đặc trị xanh" /></label>{error ? <p role="alert" className="form-alert">{error}</p> : null}<footer><button type="button" className="button" onClick={onClose}>Hủy</button><button type="submit" className="button button--primary" disabled={saving}>{saving ? "Đang lưu…" : "Lưu SKU"}</button></footer></form></div>;
}
