"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { capabilities, orgTiers, type Capability, type OrgTier } from "@/features/organization/contracts";
import { CreateAccountDialog, type CreateAccountInput } from "./create-account-dialog";
import { ReportingLineSelect } from "./reporting-line-select";

export interface OrganizationBrand { id: string; code: string; name: string }
export interface InheritedOrganizationBrand extends OrganizationBrand { sourceUserName: string }
export interface OrganizationUserDTO { id: string; displayName: string; isActive: boolean; tier: OrgTier; supervisorId: string | null; capabilities: Capability[]; directBrands: OrganizationBrand[]; inheritedBrands: InheritedOrganizationBrand[]; subordinateCount: number }
export interface OrganizationAccessDraft { userId: string; tier: OrgTier; isActive: boolean; supervisorId: string | null; capabilities: Capability[]; brandIds: string[]; replacementUserId?: string; idempotencyKey?: string }

const capabilityLabels: Record<Capability, string> = { create_annual_plan: "Tạo kế hoạch năm", view_approved_plan: "Xem kế hoạch đã duyệt", create_purchase_proposal: "Đề xuất nhập hàng", manage_master_data: "Quản lý dữ liệu nền", administer_system: "Quản trị hệ thống" };
function cloneDraft(user: OrganizationUserDTO): OrganizationAccessDraft { return { userId: user.id, tier: user.tier, isActive: user.isActive, supervisorId: user.supervisorId, capabilities: [...user.capabilities], brandIds: user.directBrands.map((brand) => brand.id) }; }

export function OrganizationAccessManager({ users, brands = [], supervisors = users, onSave, onCreateAccount }: { users: OrganizationUserDTO[]; brands?: OrganizationBrand[]; supervisors?: OrganizationUserDTO[]; onSave?: (draft: OrganizationAccessDraft) => Promise<OrganizationUserDTO>; onCreateAccount?: (input: CreateAccountInput) => Promise<void> }) {
  const createAccount = onCreateAccount ?? (async (input: CreateAccountInput) => { const response = await fetch("/api/v2/admin/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...input, emailPrefix: input.emailPrefix ?? input.email.split("@")[0], idempotencyKey: input.idempotencyKey ?? crypto.randomUUID(), capabilities: input.capabilities, brandIds: input.brandIds }) }); const payload = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(payload.error?.message ?? "Không thể tạo tài khoản."); });
  const [records, setRecords] = useState(users); const [selectedId, setSelectedId] = useState(users[0]?.id ?? ""); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all");
  const selected = records.find((record) => record.id === selectedId) ?? records[0]; const [draft, setDraft] = useState<OrganizationAccessDraft | null>(selected ? cloneDraft(selected) : null); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [replacementOpen, setReplacementOpen] = useState(false); const [replacementId, setReplacementId] = useState(""); const overrides = useRef(new Map<string, OrganizationUserDTO>());
  useEffect(() => { setRecords(users.map((user) => overrides.current.get(user.id) ?? user)); }, [users]);
  const visible = useMemo(() => records.filter((user) => user.displayName.toLocaleLowerCase("vi-VN").includes(search.trim().toLocaleLowerCase("vi-VN")) && (status === "all" || (status === "active" ? user.isActive : !user.isActive))), [records, search, status]);
  function selectUser(id: string) { const user = records.find((item) => item.id === id); if (!user) return; setSelectedId(id); setDraft(cloneDraft(user)); setMessage(null); }
  async function save() { if (!draft) return; if (draft.isActive && (draft.tier === "leader" || draft.tier === "manager") && !draft.supervisorId) { setMessage("Bắt buộc chọn người quản lý trực tiếp."); return; } if (!draft.isActive && selected && selected.subordinateCount > 0 && !replacementId) { setReplacementOpen(true); return; } const command = replacementId ? { ...draft, replacementUserId: replacementId } : draft; setSaving(true); setMessage(null); try { const canonical = onSave ? await onSave(command) : await saveRemote(command); overrides.current.set(canonical.id, canonical); setRecords((current) => current.map((user) => user.id === canonical.id ? canonical : user)); setDraft(cloneDraft(canonical)); setReplacementId(""); setMessage("Đã lưu quyền truy cập."); } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể lưu quyền truy cập."); } finally { setSaving(false); } }
  function toggleActive(value: boolean) { if (!value && selected?.subordinateCount) { setDraft((current) => current ? { ...current, isActive: false } : current); setReplacementOpen(true); } else setDraft((current) => current ? { ...current, isActive: value } : current); }
  if (!draft || !selected) return <section className="empty-state"><h2>Chưa có tài khoản để quản trị.</h2></section>;
  return <div className="organization-governance">
    <div className="organization-governance__toolbar"><label>Tìm người dùng<input aria-label="Tìm người dùng" type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tên hiển thị" /></label><label>Trạng thái<select aria-label="Trạng thái tài khoản" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Tất cả tài khoản</option><option value="active">Đang hoạt động</option><option value="inactive">Đã tạm khóa</option></select></label><CreateAccountDialog supervisors={supervisors} onCreate={createAccount} /></div>
    <div className="organization-governance__layout"><aside className="organization-user-list" aria-label="Danh sách người dùng"><p role="status">{visible.length} người dùng</p>{visible.map((user) => <button key={user.id} type="button" aria-current={user.id === selected.id ? "true" : undefined} className={user.id === selected.id ? "is-active" : ""} onClick={() => selectUser(user.id)}><strong>{user.displayName}</strong><span>{user.isActive ? "Đang hoạt động" : "Đã tạm khóa"} · {user.tier}</span></button>)}</aside>
      <section className="organization-editor"><header><p className="section-index">Quyền hiệu lực</p><h2>{selected.displayName}</h2><span className={draft.isActive ? "organization-status is-active" : "organization-status"}>{draft.isActive ? "Đang hoạt động" : "Đã tạm khóa"}</span></header>
        <label className="organization-active-toggle"><input type="checkbox" aria-label="Tài khoản đang hoạt động" checked={draft.isActive} onChange={(event) => toggleActive(event.target.checked)} /> Tài khoản đang hoạt động</label>
        <fieldset><legend>Cấp tổ chức</legend><select aria-label="Cấp tổ chức hiện tại" value={draft.tier} onChange={(event) => setDraft({ ...draft, tier: event.target.value as OrgTier, supervisorId: null })}>{orgTiers.map((tier) => <option key={tier} value={tier}>{tier}</option>)}</select></fieldset>
        <ReportingLineSelect tier={draft.tier} value={draft.supervisorId} currentUserId={draft.userId} candidates={supervisors} onChange={(value) => setDraft({ ...draft, supervisorId: value })} />
        <fieldset><legend>Capability ({draft.capabilities.length})</legend><div className="organization-option-grid">{capabilities.map((capability) => <label key={capability}><input type="checkbox" aria-label={capabilityLabels[capability]} checked={draft.capabilities.includes(capability)} onChange={(event) => setDraft({ ...draft, capabilities: event.target.checked ? [...draft.capabilities, capability] : draft.capabilities.filter((item) => item !== capability) })} /><span>{capabilityLabels[capability]}</span></label>)}</div></fieldset>
        <fieldset><legend><span>Được cấp trực tiếp</span> ({draft.brandIds.length})</legend><div className="organization-option-grid">{brands.map((brand) => <label key={brand.id}><input type="checkbox" aria-label={`${brand.code} · ${brand.name}`} checked={draft.brandIds.includes(brand.id)} onChange={(event) => setDraft({ ...draft, brandIds: event.target.checked ? [...draft.brandIds, brand.id] : draft.brandIds.filter((id) => id !== brand.id) })} /><span>{brand.code} · {brand.name}</span></label>)}</div></fieldset>
        <fieldset><legend>Quyền kế thừa</legend>{selected.inheritedBrands.length ? selected.inheritedBrands.map((brand) => <p key={`${brand.id}-${brand.sourceUserName}`}>✓ {brand.code} · {brand.name} <small>Kế thừa từ {brand.sourceUserName}</small></p>) : <p className="muted">Chưa có quyền kế thừa.</p>}</fieldset>
        {message ? <p role="status" className="form-alert">{message}</p> : null}<footer><button type="button" className="button button--primary" disabled={saving} onClick={() => void save()}>{saving ? "Đang lưu…" : "Lưu quyền truy cập"}</button></footer>
      </section>
    </div>
    {replacementOpen ? <div className="organization-dialog" role="presentation"><div className="organization-dialog__panel" role="dialog" aria-modal="true" aria-label="Chọn người quản lý thay thế"><h2>Chọn người quản lý thay thế</h2><p>Cần chuyển cấp dưới trước khi vô hiệu hóa tài khoản này.</p><select aria-label="Người quản lý thay thế" value={replacementId} onChange={(event) => setReplacementId(event.target.value)}><option value="">Chọn người thay thế</option>{supervisors.filter((user) => user.id !== selected.id && user.isActive && user.tier === selected.tier).map((user) => <option key={user.id} value={user.id}>{user.displayName}</option>)}</select><footer><button type="button" className="button" onClick={() => { setReplacementOpen(false); setReplacementId(""); }}>Hủy</button><button type="button" className="button button--primary" disabled={!replacementId} onClick={() => setReplacementOpen(false)}>Xác nhận</button></footer></div></div> : null}
  </div>;
}

async function saveRemote(draft: OrganizationAccessDraft): Promise<OrganizationUserDTO> { const response = await fetch("/api/v2/admin/users/organization", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...draft, idempotencyKey: draft.idempotencyKey ?? crypto.randomUUID() }) }); const payload = await response.json() as { data?: OrganizationUserDTO; error?: { message?: string } }; if (!response.ok || !payload.data) throw new Error(payload.error?.message ?? "Không thể lưu quyền truy cập."); return payload.data; }
